- name: Disable C-state for all CPUs
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash processor.max_cstate=1 intel_idle.max_cstate=0"'
  notify: Update GRUB
  tags: [cpu]

- name: Switch CPU governor to perfomance
  block:
    - name: Switching CPU governor to performance
      shell:
        cmd: cpupower frequency-set -g performance
      # register: performance_mode
      # changed_when: '"Success" in performance_mode.stdout'
      tags: [cpu]
  rescue:
    - name: Check available CPU governors
      shell: cpupower frequency-info -g
      changed_when: false
      failed_when: false
      register: cpu_governor
      tags: [cpu]
    - name: Display available CPU governors
      debug:
        var: cpu_governor.stdout_lines
      tags: [cpu]
  tags: [cpu]
